#!/bin/bash

# Copyright (c) 2023 PlayEveryWare
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This modifies the static site generated by docfx to correct images that are used in various places

# Path to the docfx 
PROJECT_DOCFX_PATH="etc/docfx/project"

# Copy README.md as index.md
cp README.md "$PROJECT_DOCFX_PATH/index.md"

# Generate the static site
docfx "$PROJECT_DOCFX_PATH/docfx.json"

# Copy the docs directory so that the README and other docs work properly
cp -r docs/ "$PROJECT_DOCFX_PATH/_site/docs"

# Move the pewlogo into the images directory of the generated docfx directory
cp docs/images/pewlogo.png "$PROJECT_DOCFX_PATH/_site/images/"

# Iterate through all the files that contain 'logo.svg', and replace with pewlogo.png
grep -inrl "logo.svg" "$PROJECT_DOCFX_PATH/_site/" | while read -r line ; do 
    sed -i 's/logo.svg/pewlogo.png/' $line
done

