#!/bin/bash

# This modifies the static site generated by docfx to correct images that are used in various places

# Path to the docfx 
PROJECT_DOCFX_PATH="../../etc/docfx/project"

# Copy README.md as index.md
cp ../../README.md "$PROJECT_DOCFX_PATH/index.md"

docfx $PROJECT_DOCFX_PATH

# Move the pewlogo into the images directory of the generated docfx directory
cp ../../docs/images/pewlogo.png "$PROJECT_DOCFX_PATH/_site/images/"

# Iterate through all the files that contain 'logo.svg', and replace with pewlogo.png
grep -inrl "logo.svg" "$PROJECT_DOCFX_PATH/_site/" | while read -r line ; do 
    set -i 's/logo.svg/pewlogo.png/' $line
done

